# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 22:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20161021_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='thread',
            name='modified',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
