# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 22:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_auto_20170530_2225'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['pk'], 'verbose_name_plural': 'categories'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='postCount',
        ),
        migrations.RemoveField(
            model_name='thread',
            name='postCount',
        ),
    ]
