# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 09:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_auto_20170725_2256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='markup',
        ),
    ]
