# Generated by Django 4.2.13 on 2024-06-21 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_usermentions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermentions',
            options={'ordering': ['-pk']},
        ),
    ]
