from django.conf.urls import url

from . import views


urlpatterns = [
    url(
        regex=r'^$',
        view=views.CategoryView.as_view(),
        name='top'
    ),
    url(
        regex=r'^search/$',
        view=views.SearchView.as_view(),
        name='search',
    ),
    url(
        regex=r'^(?P<category_slug>[\w|\-]+)/$',
        view=views.ThreadView.as_view(),
        name='category'
    ),
    url(
        regex=r'^(?P<category_slug>[\w|\-]+)/(?P<thread_slug>[\w|\-]+)/$',
        view=views.PostView.as_view(),
        name='thread'
    ),
    url(
        regex=r'^post/(?P<pk>[0-9]+)$',
        view=views.PostDetailView.as_view(),
        name='post'
    ),
    url(
        regex=r'^(?P<category_slug>[\w|\-]+)/\+$',
        view=views.NewThread.as_view(),
        name='new_thread'
    ),
    url(
        regex=r'^(?P<category_slug>[\w|\-]+)/\+poll$',
        view=views.NewPoll,
        name='new_poll'
    ),
    url(
        regex=r'^(?P<category_slug>[\w|\-]+)/(?P<thread_slug>[\w|\-]+)/vote/$',
        view=views.VotePoll,
        name='vote'
    ),
    url(
        regex=r'^(?P<category_slug>[\w|\-]+)/(?P<thread_slug>[\w|\-]+)/\+$',
        view=views.NewPost.as_view(),
        name='new_post'
    ),
    url(
        regex=(r'^(?P<category_slug>[\w|\-]+)/(?P<thread_slug>[\w|\-]+)/'
               r'edit=(?P<pk>\d+)$'),
        view=views.EditPost.as_view(),
        name='edit'
    ),
    url(
        regex=(r'^(?P<category_slug>[\w|\-]+)/(?P<thread_slug>[\w|\-]+)/'
               r'quote=(?P<pk>\d+)$'),
        view=views.QuotePost.as_view(),
        name='quote'
    ),
    url(
        regex=r'^reset_bookmarks/(?P<pk>[0-9]+)$',
        view=views.ResetBookmarks.as_view(),
        name='reset_bookmarks'
    ),
    url(
        regex=r'^delete_thread/(?P<pk>[0-9]+)$',
        view=views.DeleteThread.as_view(),
        name='delete_thread'
    ),
    url(
        regex=r'^preview/(?P<pk>[0-9]+)$',
        view=views.PreviewView.as_view(),
        name='preview'
    ),
]
