---
- hosts: app
  become: yes
  vars:
    network: "{{project_name}}"
  roles:
    - name: common
    - name: docker
    - name: docker_network
      networks:
        - postgres
        - nginx
        - "{{project_name}}"
    - name: postgres
      version: "13.8"
    - name: memcached
      version: "1.6"
    - name: forum
      network: "{{project_name}}"
    - name: certbot-ovh
      domains:
        - geekattitude.org
        - www.geekattitude.org
    - name: nginx
      version: "1.22"
    # - name: metrics
    #   prometheus_version: latest  # until they have a better taging policy
    #   cadvisor_version: latest    # ...
  tasks:
    # Reclaim hard drive space
    - name: clean outdated docker images & stopped containers
      shell: >
        docker system prune --force &&
        docker rmi $(docker images --quiet --filter dangling=true)
      failed_when: no
      changed_when: no
...
