# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-21 23:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forum', '0002_auto_20161021_2330'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=80, verbose_name='Titre')),
                ('content', models.TextField(max_length=100000, verbose_name='Message')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('views', models.IntegerField(default=0)),
                ('slug', models.CharField(max_length=50, unique=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogposts', to=settings.AUTH_USER_MODEL)),
                ('forum_thread', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog_post', to='forum.Thread')),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
    ]
