# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 23:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20170530_2225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forumuser',
            name='is_online',
        ),
    ]
