# Generated by Django 2.0.1 on 2018-01-27 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_forumuser_is_online'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
    ]
