# Generated by Django 4.2.13 on 2024-06-18 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20180127_0250'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='bookmark',
            new_name='user_bookma_user_id_906f3c_idx',
            old_fields=('user', 'thread'),
        ),
        migrations.RenameIndex(
            model_name='categorytimestamp',
            new_name='user_catego_user_id_942e59_idx',
            old_fields=('user', 'category'),
        ),
        migrations.AlterField(
            model_name='forumuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
