# Generated by Django 4.2.13 on 2024-06-21 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_rename_bookmark_user_thread_user_bookma_user_id_906f3c_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumuser',
            name='newMention',
            field=models.BooleanField(default=False),
        ),
    ]
