# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-21 23:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=50)),
                ('subtitle', models.CharField(max_length=200)),
                ('postCount', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='PollChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=80)),
                ('votes', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='PollQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('modified', models.DateTimeField(blank=True, null=True)),
                ('content_plain', models.TextField(max_length=100000, verbose_name='Message')),
                ('markup', models.CharField(default='bbcode', max_length=10)),
            ],
            options={
                'ordering': ['pk'],
                'get_latest_by': 'created',
            },
        ),
        migrations.CreateModel(
            name='Preview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_plain', models.TextField()),
                ('markup', models.TextField(default='bbcode')),
            ],
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('title', models.CharField(max_length=140, verbose_name='Titre')),
                ('icon', models.CharField(default='icon1.gif', max_length=80, verbose_name='Icône')),
                ('isSticky', models.BooleanField(default=False)),
                ('isLocked', models.BooleanField(default=False)),
                ('isRemoved', models.BooleanField(default=False)),
                ('viewCount', models.IntegerField(default=0)),
                ('postCount', models.IntegerField(default=0)),
                ('modified', models.DateTimeField(default=datetime.datetime.now)),
                ('personal', models.BooleanField(default=False)),
                ('visible', models.BooleanField(default=True)),
                ('cessionToken', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ['-isSticky', '-modified', 'pk'],
                'get_latest_by': 'modified',
            },
        ),
    ]
