# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-21 23:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified', models.DateTimeField(default=datetime.datetime.now)),
                ('isRemoved', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-modified'],
                'get_latest_by': 'modified',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('content_plain', models.TextField(verbose_name='Message')),
                ('markup', models.TextField(default='bbcode')),
                ('shown', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['created'],
                'get_latest_by': 'created',
            },
        ),
    ]
